name: Filter Skipped Jobs

on:
  workflow_run:
    workflows: [Workflow 1]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Commit Message
        id: check_message
        run: |
          if [[ "$(git log --format=%B -n 1 ${{ github.sha }})" =~ \[ci[ _]skip\]|\[skip[ _]ci\] ]]; then
            echo "Commit message contains [ci skip] or [skip ci]. Skipping further steps."
            echo "::set-output name=skip_steps::true"
          else
            echo "Commit message does not contain [ci skip] or [skip ci]. Proceeding with further steps."
            echo "::set-output name=skip_steps::false"
          fi
