name: Workflow 1

on:
  workflow_call:
  push:
    branches:
      - '**'
jobs:
  lints:
    runs-on: ubuntu-latest
    if: github.event.pull_request != null || github.event_name == 'push' && github.event.pull_request == null
    steps:
      - name: Your steps here
        run: echo "Workflow 1 completed ${{ github.event_name }}"
