name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' &&
      !github.event.pull_request)

    steps:
      - name: Your Step
        run: echo "Your step is executed."
