name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    steps:
      # - name: Print event details
      #   run: |
      #     echo "Runs Workflow 1"
      #     echo "Event Name: ${{ github.event_name }}"
      #     echo "Repository: ${{ github.repository }}"
      #     echo "Actor: ${{ github.actor }}"
      #     echo "Workflow: ${{ github.workflow }}"
      #     echo "Commit SHA: ${{ github.sha }}"
      #     echo "Ref: ${{ github.ref }}"
      #     echo "Head Ref: ${{ github.head_ref }}"
      #     echo "Base Ref: ${{ github.base_ref }}"
      - name: Search Pull Requests
        id: search_prs
        run: |
          gh pr list --search "${{ github.ref }}"
          echo "::set-output name=success::true"
        continue-on-error: true # Continue to the next step even if the PR search fails

      - name: Check if PR search succeeded
        if: steps.search_prs.outputs.success == 'true'
        run: echo "PR search succeeded. Continuing with further processing."

      - name: Skip further processing if PR search failed
        if: steps.search_prs.outputs.success != 'true'
        run: echo "PR search failed. Skipping further processing."
