name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        id: get_pull_requests
        run: |
          PR_URL="https://api.github.com/repos/4stein/test-workflow-after-workflow/pulls?state=open"
          PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$PR_URL")
          echo "Pull Requests Data:"
          echo "$PR_DATA"
          echo "::set-output name=pull_requests::$PR_DATA"

      - name: Check if branch is in pull requests
        run: |
          BRANCH_REF="${{ github.ref }}"
          PR_DATA="${{ steps.get_pull_requests.outputs.pull_requests }}"

          echo "Branch Reference: $BRANCH_REF"
          echo "Pull Requests Data:"
          echo "$PR_DATA"

          # Proceed with parsing JSON only if the response format is valid
          if [[ "$PR_DATA" =~ ^\[.*\]$ ]]; then
            HEAD_REFS=$(echo "$PR_DATA" | jq -r '.[] | .head.ref')
            echo "Head Refs:"
            echo "$HEAD_REFS"

            BRANCH_IN_PR=$(echo "$HEAD_REFS" | grep -q "$BRANCH_REF" && echo "true" || echo "false")

            if [ "$BRANCH_IN_PR" == true ]; then
              echo "Branch $BRANCH_REF is included in at least one open pull request."
            else
              echo "Branch $BRANCH_REF is not included in any open pull request."
            fi
          else
            echo "Cannot proceed with parsing JSON due to incomplete or improperly terminated response."
          fi
