name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' || # Skip workflow if it's a pull request event
      (
        github.event_name == 'push' &&  # Proceed if it's a push event
        !(github.event.pull_request)   # Skip workflow if there's no associated pull request
      )

    steps:
      - name: Your Step
        run: echo "Your step is executed."
