name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    branches:
      - '**'
  pull_request:
    types: [opened]

jobs:
  lints:
    # if: needs.pr-check.outputs.number != null
    runs-on: ubuntu-latest
    outputs:
      is_in_pr: ${{ steps.set_variable.outputs.is_in_pr }}
    steps:
      - name: Print event details
        run: |
          echo "Runs Workflow 1"
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
      - name: 'Set Variable - Pull Request ${{ steps.PR.outputs.number }}'
        id: set_variable
        run: |
          echo "::set-output name=is_in_pr::${{ steps.PR.outputs.pr_found}}"
      - name: Here is a next step
        run: |
          echo "Variable received: ${{ steps.PR.outputs.pr_found }}"
  # build:
  #   needs: [lints]
  #   if: needs.job1.outputs.is_in_pr != 'true'
  #   uses: ./.github/workflows/workflow2.yml
  build:
    name: build
    needs: [lints]
    if: needs.job1.outputs.is_in_pr
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 2 triggered by Workflow 1 completion ${{ needs.lints.outputs.is_in_pr }}"
