name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch is in pull request
        id: check_branch
        run: |
          # Make the curl request to list pull requests for the repository
          PR_URL=$(curl -s -X GET "${{ github.api_url }}/repos/${{ github.repository }}/pulls?state=open" \
                  -H "Authorization: token ${{ github.token }}" \
                  -H "Accept: application/vnd.github.v3+json")

          # Check if the branch is associated with any open pull requests
          PR_FOUND=$(echo "$PR_URL" | jq --arg branch "${{ github.ref }}" '.[] | select(.head.ref == $branch) | length')

          if [ "$PR_FOUND" -gt 0 ]; then
            echo "Branch is associated with an open pull request."
            echo "::set-output name=branch_in_pr::true"
          else
            echo "Branch is not associated with any open pull request."
            echo "::set-output name=branch_in_pr::false"
          fi

      - name: Use the result
        if: steps.check_branch.outputs.branch_in_pr == 'true'
        run: echo "Branch is in a pull request."
