name: Test Build DEV Backstage IOS and Android
on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  linter:
    uses: ./.github/workflows/workflow2.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  build_android:
    needs: [linter]
    env:
      ZELUS_PAT_TOKEN: ${{ secrets.PAT }}
    name: Android build
    runs-on: ubuntu-latest
    steps:
      - name: Start Android Build
        env:
          ZELUS_PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Run Android Build"
  build_ios:
    needs: [linter]
    name: IOS build
    runs-on: ubuntu-latest
    steps:
      - name: Start IOS Build
        run: |
          echo "Run IOS Build"

  #---------------------------------------------------------#
  # filter_jobs:
  #   needs: [lints]
  #   uses: ./.github/workflows/hideskipped.yml
  # java-build:
  #   needs: [lints]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print event details
  #       run: |
  #         ${{ jobs.lints.result == 'success' }}
  #---------------------------------------------------------#
  # - name: Trigger Deployment
  #   run: |
  #     curl -X POST \
  #       -H "Authorization: Bearer ${{ github.token }}" \
  #       -H "Accept: application/vnd.github.everest-preview+json" \
  #       -H "Content-Type: application/json" \
  #       https://api.github.com/repos/4stein/test-workflow-after-workflow/dispatches \
  #       --data '{"event_type": "start-deployment"}'
