name: Workflow 1

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 1 completed"
