name: Workflow 1

on:
  # permissions:
  #   pull-requests: none
  push:
    #   branches:
    #     - '**'
    branches-ignore:
      - main
  # types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Build
        run: |
          # Your build commands here
          echo "Building..."
