name: Workflow 1

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Your steps here
        run: echo "Workflow 2 triggered by Workflow 1 completion"
      - name: Trigger Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/4stein/test-workflow-after-workflow/dispatches \
            --data '{"event_type": "start-deployment"}'
  # build:
  #   needs: [lints]
  #   if: needs.lints.outputs.is_in_pr == 'true'
  #   uses: ./.github/workflows/workflow2.yml

  # filter_jobs:
  #   needs: [lints]
  #   uses: ./.github/workflows/hideskipped.yml
  # java-build:
  #   needs: [lints]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print event details
  #       run: |
  #         ${{ jobs.lints.result == 'success' }}
