name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    branches:
      - '**'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_variable.outputs.my_variable }}

    steps:
      - name: Set Variable
        id: set_variable
        run: |
          echo "::set-output name=my_variable::${{1 == 1}}"

      # You can also save variables as artifacts
      - name: Save Variable as Artifact
        run: |
          echo "Variable received: ${{ needs.job1.outputs.my_variable }}"
        # Store the variable.txt file as an artifact
        # This will make it available to subsequent jobs
        # You can also define path and name for artifacts
        # - name: Upload Artifact
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: my-artifact
        #     path: variable.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Get Variable
        run: |
          echo "Variable received: ${{ needs.job1.outputs.my_variable }}"
