name: Workflow 1

on:
  workflow_call:
  push:
    branches:
      - '**'
  pull_request:
    branches-ignore:
      - main
jobs:
  lints:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.event.pull_request == null || github.event_name == 'pull_request' && github.event.pull_request != null
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch is in pull request
        id: check_pr
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          pull_requests=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${branch_name}")
          if [ "$(echo $pull_requests | jq length)" -gt 0 ]; then
            echo "Branch is in pull request."
            echo "::set-output name=in_pull_request::true"
          else
            echo "Branch is not in pull request."
            echo "::set-output name=in_pull_request::false"
          fi

      - name: Run workflow if branch is in pull request
        if: steps.check_pr.outputs.in_pull_request == 'true'
        run: |
          # Your workflow steps here
