name: Linter

on:
  workflow_call:
  pull_request:
    types: [opened]

jobs:
  # if: github.event.pull_request != null
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Start linter
        run: echo "Run Linter"
