name: Workflow 2

on:
  workflow_call:
  pull_request:
    types: [opened]

jobs:
  # if: github.event.pull_request != null
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 2 triggered by Workflow 1 completion ${{ github.event.pull_request.number}}"
