name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        run: |
          PR_URL=$(curl -s -w "%{http_code}" -X GET "${{ github.api_url }}/repos/${{ github.repository }}/pulls?state=open" \
                    -H "Authorization: token ${{ github.token }}" \
                    -H "Accept: application/vnd.github.v3+json")
          HTTP_STATUS="${PR_URL: -3}" # Get the last 3 characters which are the HTTP status code
          PR_URL="${PR_URL::-3}"       # Remove the last 3 characters which are the HTTP status code
          echo "Pull Requests Response (HTTP Status Code: $HTTP_STATUS):"
          echo "$PR_URL"
          echo "::set-output name=pull_requests::$PR_URL"

      - name: Check if branch is in pull requests
        run: |
          BRANCH_REF="${{ github.ref }}"
          PR_DATA="${{ steps.get_pull_requests.outputs.pull_requests }}"

          echo "Branch Reference: $BRANCH_REF"
          echo "Pull Requests Data:"
          echo "$PR_DATA"

          if [ -z "$PR_DATA" ]; then
            echo "Failed to retrieve pull requests data. HTTP Status Code: $HTTP_STATUS"
            exit 1
          fi

          HEAD_REFS=$(echo "$PR_DATA" | jq -r '.[] | .head.ref')
          echo "Head Refs:"
          echo "$HEAD_REFS"

          BRANCH_IN_PR=$(echo "$HEAD_REFS" | grep -q "$BRANCH_REF" && echo "true" || echo "false")

          if [ "$BRANCH_IN_PR" == true ]; then
            echo "Branch $BRANCH_REF is included in at least one open pull request."
          else
            echo "Branch $BRANCH_REF is not included in any open pull request."
          fi
