name: Linter

on:
  workflow_call:
    secrets:
      TEST_SECRET:
        required: true
jobs:
  linter:
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
      - name: Step 1
        run: |
          if [ "${{ secrets.PAT }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
