name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    branches:
      - '**'
jobs:
  lints:
    # if: needs.pr-check.outputs.number != null
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_variable.outputs.my_variable }}

    steps:
      - name: Set Variable
        id: set_variable
        run: |
          echo "::set-output name=my_variable::Hello from Job 1"
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Get Variable
        run: |
          echo "Variable received: ${{ needs.job1.outputs.my_variable }}"
