name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }} # Setting the GH_TOKEN environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Adding this step to checkout the repository

      - name: Search Pull Requests
        id: lints
        run: |
          gh pr list --search "${{ github.sha }}"
          echo "::set-output name=success::true"
        continue-on-error: true # Continue to the next step even if the PR search fails

      - name: Check if PR search succeeded
        if: steps.lints.outputs.success == 'true'
        run: echo "PR search succeeded. Continuing with further processing."

      - name: Skip further processing if PR search failed
        if: steps.lints.outputs.success != 'true'
        run: echo "PR search failed. Skipping further processing."
