name: Linter

on:
  push:
    branches:
      - '**'

jobs:
  # if: github.event.pull_request != null
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Start linter
        run: echo "Run Linter"
