name: Linter

on:
  workflow_call:
    ZELUS_PAT_TOKEN:
      required: true
  push:
    branches-ignore:
      - test

jobs:
  # if: github.event.pull_request != null
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Start linter
        env:
          ZELUS_PAT_TOKEN: ${{ secrets.PAT }}
        run: echo "Run Linter"
