name: Linter

on:
  workflow_call:
    secrets:
      PAT:
        required: true
  push:
    branches-ignore:
      - test
jobs:
  linter:
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
      - name: Step 1
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          if [ "${{ secrets.PAT }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
