name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        run: |
          PR_URL=$(curl -s -X GET "${{ github.api_url }}/repos/${{ github.repository }}/pulls?state=open" \
                    -H "Authorization: token ${{ github.token }}" \
                    -H "Accept: application/vnd.github.v3+json")
          echo "Pull Requests Response:"
          echo "$PR_URL"

      - name: Check if branch is in pull requests
        run: |
          BRANCH_REF="${{ github.ref }}"
          echo "Branch Reference: $BRANCH_REF"
