name: Workflow 1

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.pull_request == null || github.event_name == 'pull_request' && github.event.pull_request != null
    steps:
      - name: Print event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base Ref: ${{ github.base_ref }}"
