name: Workflow 2

on:
  pull_request:
    branches:
      - '**'

jobs:
  # lints:
  #   uses: ./.github/workflows/workflow3.yml
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 2 triggered by Workflow 1 completion"
