name: Workflow 2

on:
  push:
    branches:
      - '**'

jobs:
  lints:
    uses: ./.github/workflows/workflow1.yml
  build:
    name: build
    needs: [lints]
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 2 triggered by Workflow 1 completion"
