name: Workflow 1

on:
  workflow_call:
  push:
    branches:
      - '**'

jobs:
  lints:
    if: github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Your steps here
        run: echo "Workflow 1 completed ${{ github.event_name }}"
