name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    branches:
      - '**'
jobs:
  lints:
    # if: needs.pr-check.outputs.number != null
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_variable.outputs.my_variable }}

    steps:
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      # - name: 'Set Variable - Pull Request ${{ steps.PR.outputs.number }}'
      #   id: set_variable
      #   run: |
      #     echo "::set-output name=my_variable::Hello from Job 1"
      - name: Set Variable
        id: set_variable
        run: |
          echo "::set-output name=my_variable::Hello from Job 1"
  build:
    needs: lints
    runs-on: ubuntu-latest

    steps:
      - name: Get Variable
        run: |
          echo "Variable received: ${{ needs.lints.outputs.my_variable }}"
