name: Workflow 1

on:
  push:
    # branches:
    #   - '**/pull/**' # Ignore branches with 'pull' in their name
    # branches:
    #   - '**'
  # pull_request:
  #   branches-ignore:
  #     - main
  workflow_call:
jobs:
  lints:
    # if: needs.pr-check.outputs.number == null
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        id: get_pull_requests
        run: |
          PR_RESPONSE=$(curl -s -w "%{http_code}" -X GET "${{ github.api_url }}/repos/${{ github.repository }}/pulls?state=open" \
                        -H "Authorization: token ${{ github.token }}" \
                        -H "Accept: application/vnd.github.v3+json")
          HTTP_STATUS="${PR_RESPONSE:(-3)}" # Get the last 3 characters which are the HTTP status code
          PR_DATA="${PR_RESPONSE:0:(-3)}"    # Remove the last 3 characters which are the HTTP status code
          echo "Pull Requests Response (HTTP Status Code: $HTTP_STATUS):"
          echo "$PR_DATA"
          echo "::set-output name=pull_requests::$PR_DATA"
          echo "::set-output name=http_status::$HTTP_STATUS"

      - name: Check response completeness
        run: |
          PR_DATA="${{ steps.get_pull_requests.outputs.pull_requests }}"

          # Check if the response contains both the opening and closing square brackets
          if [[ "$PR_DATA" =~ ^\[.*\]$ ]]; then
            echo "The response seems to be properly formed."
          else
            echo "The response may be incomplete or improperly terminated."
          fi

      - name: Check if branch is in pull requests
        if: ${{ steps.get_pull_requests.outputs.http_status == '200' }}
        run: |
          BRANCH_REF="${{ github.ref }}"
          PR_DATA="${{ steps.get_pull_requests.outputs.pull_requests }}"

          echo "Branch Reference: $BRANCH_REF"
          echo "Pull Requests Data:"
          echo "$PR_DATA"

          # Proceed with parsing JSON only if the response format is valid
          if [[ "$PR_DATA" =~ ^\[.*\]$ ]]; then
            HEAD_REFS=$(echo "$PR_DATA" | jq -r '.[] | .head.ref')
            echo "Head Refs:"
            echo "$HEAD_REFS"

            BRANCH_IN_PR=$(echo "$HEAD_REFS" | grep -q "$BRANCH_REF" && echo "true" || echo "false")

            if [ "$BRANCH_IN_PR" == true ]; then
              echo "Branch $BRANCH_REF is included in at least one open pull request."
            else
              echo "Branch $BRANCH_REF is not included in any open pull request."
            fi
          else
            echo "Cannot proceed with parsing JSON due to incomplete or improperly terminated response."
          fi
